apiVersion: v1
kind: Service
metadata:
  namespace: k8s-demo
  labels:
    io.kompose.service: app
  name: app
spec:
  type: LoadBalancer
  ports:
  - name: "node-app-service"
    port: 9010
    targetPort: 9000
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
