apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\rramo\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "8200"
    port: 8200
    targetPort: 8000
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
