apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: octavia
  annotations:
    kubernetes.io/ingress.class: "openstack"
    octavia.ingress.kubernetes.io/internal: "false"
spec:
  defaultBackend:
    service:
      name: php-nginx
      port:
        number: 9200