apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    selector: php-db-app
  name: php-db-app
  namespace: k8s-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: cinder-default
status: {}