apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    selector: php-db-app
  name: php-db-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-sc-cinderplugin
status: {}