apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: k8s-demo
  labels:
    selector: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      selector: node-app
  template:
    metadata:
      labels:
        selector: node-app
    spec:
      containers:
      - env:
        - name: PGDATABASE
          value: postgres
        - name: PGHOST
          value: node-db
        - name: PGPORT
          value: "5432"
        - name: PGPASSWORD
          value: example
        - name: PGUSER
          value: postgres
        image: ghcr.io/rramo012/node-app:latest
        name: node-app
        ports:
        - containerPort: 9000
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
status: {}
