apiVersion: v1
kind: ConfigMap
metadata:
  name: node-db-initialization
  namespace: k8s-demo
data:
  init-database.sql: |
            CREATE TABLE IF NOT EXISTS traffic (
                id SERIAL,
                hostname TEXT NOT NULL,
                created_at timestamp
            );

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-demo
  labels:
    selector: node-db
  name: node-db
spec:
  replicas: 1
  selector:
    matchLabels:
      selector: node-db
  strategy: {}
  template:
    metadata:
      labels:
        selector: node-db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: example
        - name: POSTGRES_USER
          value: postgres
        image: postgres:13.3
        imagePullPolicy: ""
        name: db
        resources: {}
        volumeMounts:
          - name: node-db-initialization
            mountPath: /docker-entrypoint-initdb.d/init-database.sql
            subPath: init-database.sql
          - name: node-db-pvc
            mountPath: /var/lib/postgresql/data
            subPath: postgres
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: node-db-initialization
          configMap:
            name: node-db-initialization
            items:
              - key: init-database.sql
                path: init-database.sql
        - name: node-db-pvc
          persistentVolumeClaim:
            claimName: node-db-app
            readOnly: false
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: node-db
  namespace: k8s-demo
  labels:
    selector: node-db
spec:
  ports:
  - name: "node-db"
    port: 5432
  selector:
    selector: node-db
