apiVersion: v1
kind: Service
metadata:
  namespace: k8s-demo
  labels:
    selector: python-app
  name: python-app-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: "python-app-load-balancer"
    port: 9400
    targetPort: 80
  selector:
    selector: python-app
status:
  loadBalancer: {}
