apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-python-db
  namespace: k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /data/pv-python-db/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    selector: python-db-app
  name: python-db-app
  namespace: k8s-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-python-db
status: {}