apiVersion: v1
kind: Service
metadata:
  labels:
    selector: node-app
  name: node-app
  namespace: k8s-demo
spec:
  type: NodePort
  ports:
  - name: "nodejs-node-port"
    port: 9000
  selector:
    selector: node-app

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-app-octavia
  namespace: k8s-demo
  annotations:
    kubernetes.io/ingress.class: "openstack"
    octavia.ingress.kubernetes.io/internal: "false"
spec:
  backend:
    serviceName: node-app
    servicePort: 9000
