apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: k8s-demo
  labels:
    selector: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      selector: php-fpm
  strategy: {}
  template:
    metadata:
      labels:
        selector: php-fpm
    spec:
      containers:
      - env:
        - name: DB_SERVER
          value: php-db
        image: ghcr.io/rramo012/php-app:latest
        name: app
        ports:
        - containerPort: 9000
        resources: {}
        tty: true
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: k8s-demo
  labels:
    selector: php-fpm
spec:
  ports:
  - name: "php-fpm"
    port: 9000
  selector:
    selector: php-fpm
status:
  loadBalancer: {}
