apiVersion: v1
kind: Service
metadata:
  namespace: k8s-demo
  labels:
    selector: node-app
  name: node-app-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: "node-app-load-balancer"
    port: 9300
    targetPort: 9000
  selector:
    selector: node-app
status:
  loadBalancer: {}
