apiVersion: v1
kind: Service
metadata:
  labels:
    selector: python-app
  name: python-app
  namespace: k8s-demo
spec:
  type: NodePort
  ports:
  - name: python-app
    port: 80
  selector:
    selector: python-app

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: python-app-octavia
  namespace: k8s-demo
  annotations:
    kubernetes.io/ingress.class: "openstack"
    octavia.ingress.kubernetes.io/internal: "false"
spec:
  backend:
    serviceName: python-app
    servicePort: 80
