apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    selector: python-db-app
  name: python-db-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-sc-cinderplugin
status: {}