apiVersion: v1
kind: Service
metadata:
  namespace: k8s-demo
  labels:
    selector: php-nginx
  name: php-nginx-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: "nginx-load-balancer"
    port: 9200
    targetPort: 80
  selector:
    selector: php-nginx
status:
  loadBalancer: {}
