apiVersion: v1
kind: Service
metadata:
  namespace: k8s-demo
  labels:
    io.kompose.service: nginx
  name: php-nginx-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: "nginx-load-balancer"
    port: 9200
    targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
