apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-php-db
  namespace: k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /data/pv-php-db/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    selector: php-db-app
  name: php-db-app
  namespace: k8s-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-php-db
status: {}