version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    command: "uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
       - ./app:/app
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: example
    ports:
      - 8200:8000

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ../../database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080

volumes:
  db:
    driver: local
